version: '3.7'
services:

  app:
      build:
        context: ./
        dockerfile: Dockerfile
      image: gdd/laravel
      container_name: myapp
      restart: unless-stopped
      tty: true
      environment:
        SERVICE_NAME: myapp
        SERVICE_TAGS: dev
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
      networks:
        - mynet

  db:
      image: mysql
      restart: always
      tty: true
      ports:
        - "5432:5432"
      environment:
        MYSQL_USER: root
        MYSQL_DB: app
        MYSQL_PASSWORD: password
        MYDATA: /var/lib/mysql/data/mydata
        MYSQL_HOST_AUTH_METHOD: trust
      volumes:
        - mysqldata:/var/lib/mysql/data

