---
  name: Deploy
  on:
    push:
      branches:
        - main
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            tools: composer:v2
            coverage: none
        - name: Install Composer dependencies
          run: composer install --prefer-dist --no-interaction --no-dev
        - name: Require Vapor CLI
          run: composer global require laravel/vapor-cli
        - name: select team
          run: vapor login
          env:
            Email_Address: K.tchakpele@gmail.com
            Password: Elsenior@1995
        - name: Deploy Environment
          run: vapor deploy
          env:
            VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
  