name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cp .env.example .env
          php artisan key:generate
          sudo apt-get install php
          sudo apt-get install php-xml
          sudo apt-get install php-curl
          sudo apt-get install php-mysql
          sudo apt install mysql-server
          sudo apt-get install php-mbstring
          sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          sudo composer update --no-interaction
          sudo composer install --no-interaction --prefer-dist
          ls -a
          cat .env
          sudo systemctl start mysql
          systemctl status mysql
          php artisan cache:clear
          php artisan config:clear
          sudo php artisan migrate --force
      
      - name: Run test
        run: php artisan test
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: job_front
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

 
      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: dist/
          target: /tmp/dist/

      - name: Deploy frontend and backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /tmp/dist/dist/endless
            sudo service nginx stop
            sudo cp -r .* /var/www/html/
            cd /var/www/backend/Job_Secure
            git pull
            sudo killall -9 php
            sudo kill $(sudo lsof -t -i:8000)
            sudo composer update --no-interaction
            sudo composer install --no-interaction --prefer-dist
            sudo php artisan migrate --force
            sudo php artisan serve > /dev/null 2>&1 &
            sudo service nginx start
            


      
